<?php

declare(strict_types=1);

namespace Anthropic\Beta\Messages;

use Anthropic\Core\Attributes\Api;
use Anthropic\Core\Concerns\SdkModel;
use Anthropic\Core\Contracts\BaseModel;

/**
 * Tool invocation generated by a server-side tool.
 *
 * @phpstan-type BetaServerToolCallerShape = array{
 *   tool_id: string, type: 'code_execution_20250825'
 * }
 */
final class BetaServerToolCaller implements BaseModel
{
    /** @use SdkModel<BetaServerToolCallerShape> */
    use SdkModel;

    /** @var 'code_execution_20250825' $type */
    #[Api]
    public string $type = 'code_execution_20250825';

    #[Api]
    public string $tool_id;

    /**
     * `new BetaServerToolCaller()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * BetaServerToolCaller::with(tool_id: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new BetaServerToolCaller)->withToolID(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     */
    public static function with(string $tool_id): self
    {
        $obj = new self;

        $obj['tool_id'] = $tool_id;

        return $obj;
    }

    public function withToolID(string $toolID): self
    {
        $obj = clone $this;
        $obj['tool_id'] = $toolID;

        return $obj;
    }
}
